name: Run Integration Test
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 24
      uses: actions/setup-java@v4
      with:
        java-version: '24'
        distribution: 'corretto'

    # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4 # v4.0.0
      with:
        gradle-version: '8.14.3'

    - name: Build with Gradle Wrapper
      env:
        API_CONFIG_WEATHERSTACK_KEY: ${{ secrets.WEATHERSTACK_API_KEY }}
        API_CONFIG_OPENWEATHER_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
        SPRING_PROFILES_ACTIVE: integration
      run: ./gradlew integrationTest
